### ISSUE TITLE
Aquilo generation changes

### ISSUE THREAD

**Issue by DavidSarif** [Frontrider/dea-dia-system#16]
As Dea Dia mod uses Frost Biters as dependency, Aquilo terrain generation is changed: there is a lot of solid land at any settings. However, there are no frost biters on the planet. Is it possible to revert Aquilo terrain to the vanilla ammonia sea type?

**Comment by Frontrider** [comment]
That issue was fixed with the latest release, you can manually reset frost biter config settings. I'm still gonna re-check it if I'm hiding the surface setting or not, it should be forced to "nauvis" by now which resolves this issue.

On an existing save where frost biters already applied this change I have nothing that I can do. The game has a system where if worldgen is updated then the surface stays on the old generation to protect old 1.1 nauvis saves.
You'll have to delete that surface in editor mode to fix it.

I'll give you another comment when I verified my fix again.

**Comment by DavidSarif** [comment]
With 0.25.0 the situation is still the same. With "nauvis" in frost biters settings Aquilo generation is solid land: both on existing save when new surface is generated via editor and in fresh sandbox-mode save.

Sorry, if my comments are too annoying: I just got Aquilo planet unlock and can not wait to start this planet with all new toys from planet mods.

**Comment by Frontrider** [comment]
I'll need a save then.

**Comment by DavidSarif** [comment]
Save attached. Activated editor, deleted all surfaces and emptied Nauvis to reduce filesize. It should not have influence on the issue (I hope). I can provide full save if needed, but it is 75 MB.

[Nauvis for git 2.zip](https://github.com/user-attachments/files/19622000/Nauvis.for.git.2.zip)

**Comment by Frontrider** [comment]
I'm only interested in the settings. The save may have it locked to something other than Nauvis.
I'll check it as soon as I can.

**Comment by DavidSarif** [comment]
Made some additional research and tried different settings on new games. Set game scenario as sandbox, generated planets with editor "Generate planets" button.
The Frost biter generation setting is on "both" (default), frost biter surface temp setting unchecked: no frost biters both on Aquilo and Lemures, Aquilo modified.
The Frost biter generation setting is on "both" (default), frost biter surface temp setting checked: frost biters only on Lemures, Aquilo modified.
The Frost biter generation setting is on "Lemures", frost biter surface temp setting checked: frost biters only on Lemures, Aquilo modified.
The Frost biter generation setting is on "Nauvis", frost biter surface temp setting checked or unchecked: game does not start and shows error "Failed to load mods: Error while running setup for space-location prototype "lemures" (planet): "frost_enemy_base" is not a valid autoplace control name."

**Comment by Frontrider** [comment]
I no longer set it to lemures after talking to Ferrari, Nauvis is the correct choice.

The aquilo generation will be updated if you set it to "both", no frost biters will show up on Lemures if you don't ignore temperature settings.

I'll may also end up dropping frost biters, as I do not know what their fate should be with a few changes that I want to include later, but I am very unsure.

**Comment by Frontrider** [comment]
Found the exact issue, if it is not set to aquillo, then the whole thing breaks on my side...

**Comment by Frontrider** [comment]
this is for one fixed on the frost biter side, for two they are removed in the next iteration.
